# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: cyrille.midingoyi@cirad.fr
author_name: Cyrille Midingoyi
create_claude_symlink: true
create_gemini_symlink: true
has_ai_rules: true
has_binder: true
has_settings: true
kind: frontend-and-server
labextension_name: cropmstudio
project_short_description: A JupyterLab extension.
python_name: cropmstudio
repository: https://github.com/AgriculturalModelExchangeInitiative/cropmstudio
test: true

